import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { PlayersProvider } from './context/playersContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-screen h-screen bg-game-bg">
        <PlayersProvider>{children}</PlayersProvider>
      </body>
    </html>
  );
}
