
import localFont from "next/font/local";

const playerFont = localFont({
  src: '../static-fonts/That Sounds Great.otf',
  display: 'swap',
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, players, scoreboard }) {
  return (
    <div className="flex bg-game-bg w-full h-full overflow-hidden ">
        
          {children}
          <div className='flex '>
            <div className="w-3/4 h-full ">
              {players}
            </div>
            <div className="w-1/4 h-full">
            {scoreboard}
            </div>  
          </div>
        
    </div>
  );
}
